### ISSUE TITLE
Which versions of node should guerilla work with?

### ISSUE THREAD

**Issue by seyeojumu** [yahoo/guerilla#42]
A [recent PR](https://github.com/yahoo/guerilla/blob/master/routes/master/workers.js#L20) used `String.prototype.includes`, an [ES6 feature](https://developer.mozilla.org/en-US/docs/Web/JavaScript/New_in_JavaScript/ECMAScript_6_support_in_Mozilla#Additions_to_the_String_object).

Running [node 0.12 ](http://stackoverflow.com/questions/28388885/ecmascript-6-features-available-in-node-js-0-12) with `--harmony` adds `String.prototype.contains`, not the the standard's `.includes`.

Which node versions are supported / how guerilla is supposed to be run?

**Comment by nickwph** [comment]
it works with 5.7.0 and 5.6.0 on my machine. but i don't know what exact versions it is supposed to be run.

**Comment by BruceBGordon** [comment]
We need a philosophy. I suggest that we try to stick to the latest stable release of Node, backing off when we have to.

**Comment by vpulim** [comment]
I think we should try not to use new ES6 features whenever possible as many users of guerilla may be running older versions and/or may not be able to upgrade for various reasons.  In the case of String.prototype.includes, indexOf() works just as well.

**Comment by BruceBGordon** [comment]
A hard call. I would like to improve our productivity and code clarity, and recent enhancements like maps help out there.  I've been assuming (perhaps wrongly) that we would run on the latest and there may be some ES6 creep already! 

```
On Wednesday, March 2, 2016 11:35 AM, Vinay Pulim <notifications@github.com> wrote:
```

 I think we should try not to use new ES6 features whenever possible as many users of guerilla may be running older versions and/or may not be able to upgrade for various reasons. In the case of String.prototype.includes, indexOf() works just as well.—

**Comment by seyeojumu** [comment]
How about this? For now, guerilla should run on 0.12, w/o the harmony flag. That won't break any existing  uses, `Map` for instance. I can make the changes and cut a PR.

Then, to future proof, something like [babel](https://babeljs.io/) can be added, to allow es6 features to work with the engines currently in use.

Then, either aligned to the LTS schedule or whenever people decide, the engine version can cut over and babel can be removed.

/cc @thekushpatel

**Comment by vpulim** [comment]
@seyeojumu: i like that plan

**Comment by thekushpatel** [comment]
@seyeojumu agreed, solid plan. would be awesome if you could make those changes and make a note of that in the docs.

**Comment by seyeojumu** [comment]
done #43 #44
